### ISSUE TITLE
Code generation workflow

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#70] opened 2016-08-03 16:34 UTC
@ggorman @navjotk @mlange05 
This is a general concern about the generation part. We do have a really nice tool however there is a few flags that will hit us hard if we don't look at it now. I will work on it a lot but some of it is completely out of my skills and knowledge to do anything about it.  Feel free to add anyone to this issue.

**The first one** concern the symbolic expressions handling. It seems like the PDE stencils are not treated the same way as the src/rec and some other stencil.
one example is :
`eqn = m * v.dt2 - v.laplace - damp * v.dt`
`stencil = solve(eqn, v.backward)[0]`
`# Add Gradient-specific updates. The dt2 is currently hacky as it has to match the cyclic indices`
`gradient_update = Eq(grad, grad - s**-2*(v + v.forward - 2 * v.forward.forward) * u.forward)`
`stencils = [gradient_update, Eq(v.backward, stencil)]``

The actual stencil 'stencil' will be treated properly as designed for, however `gradient_update` won't because the left-hand side is not time dependent. This leads to this `(v + v.forward - 2 * v.forward.forward) * u.forward` that should only be `v.dt2 * u`. The reason being `gradient_update` completly skip the cyclic indexing forcing to look into the c code and force by hand the correct indices. This make the symbolic expression complely wrong from the mathematical point of view and defeat the purpose of it.

This problem also rises with the source/reciever part that is hard-coded to be injected t (translated to t2 in code) no matter what you want to do.

**The second** issue is mostly due to the Born function. As it is written in the python code `Acoustic2D.py` the computations is :
1- compute stencil 1 (u)
2- Add source to u
3- Compute stencil 2 (U)
4- add source to U
5-  read data from U

The way it is currently implemente, it switch 1 and 2 and do 1,3,4 within the spacial loops. This does not do the same as the source for U depends on u and require u to have the source added. The only way to do that, is to do it like in the python and to do a first full spacial loop for the first stencil, add the source, and do a full second spatial loop for U. This is not currently possible in our workflow as it is solely based on 
A pre-stencils
B stencils
C post-stencils

with no possibility to split the stencils part and add intermediate computations.

**Finally** i think our data structure have to me modified. There is a lot of copying and redundancy e.g
`self.rec = SourceLike(name="rec", npoint=self.nrec, nt=self.nt, dt=self.dt, h=self.h,
                              coordinates=self.data.receiver_coords, ndim=len(dimensions), dtype=self.dtype,
                              nbpml=nbpml)`

I do not understand why a source structure would require nbpml or h.
the rest of the data concern is  in issue #66

**Comment by mlange05** [comment] 2016-08-04 08:31
Ok, first of all it is important to remember that the current symbolic automation is very much a work in progress and that we are spending only limited resources on it at the moment. However, this issue will be great for tracking further requirements, so thanks for creating it in this detail. Now for your points:

1) Yes, there is different treatment of different types of SymPy expressions and some of this is by design to accommodate the **principle of graceful degradation** approach. The key idea is that not everything can be expressed neatly as a "pure" SymPy expression using our provided derivative symbols, especially with respect to the time discretisation as you pointed out, so we provide a second layer that allows you to "hand-craft" the stencil yourself. The two layers effectively are:
* The high-level API in *Operator* takes the expansions of our derivative symbols plus some generic SymPy expressions, where data objects, like `u` and `v` are `TimeData` or `DenseData` objects with associated data, behave like *Functions* and the stencil indices are defined in terms of `s` (time) and `h` (space), eg. `u(t + s, x + 2h, y)`.
* The expressions the *Propagator* requires are a bit more restricted, in that the data symbols look like code, behave like *matrix accesses* and have no data attached (they are simply `sympy.Indexed`/`IndexedBase` objects), ie. `u[t+1, x, y]`

The reason for this separation is that for things we cannot yet cleanly express in high-level "Operator-speak", we can simply construct the more low-level Propagator expressions by hand, as the `sympy_smart_replace` methods did previously. For Acoustic FWI, the gradient update stencil is still kept in the low-level "indexed access" form, which is ignored by the Operator and passed straight into the Propagator. The new src/rec stencils in FWI are also created in this low-level form, which allows the time index to be set/changed explicitly, for example `src[t + 1, p] = some_stuff * u[t - 2, x, y, z]`. 

The reason I have not switched these parts of the kernel to the Operator-style API are exactly the time discretisation problems you mentioned. For example, `u.forward` is just short-hand for "the highest index in the 1D time stencil", which for a second order scheme will always got to `t + 2`. I have not yet thought too much about how this generalises, but I would obviously be grateful for any suggestions.

**Comment by mlange05** [comment] 2016-08-04 09:11
2) Your second point actually touches on two design issues that I have planned:
* We currently hard-code the order of the dimensions and therefore "fix" the exact order and form of the inner loop nest. My plan to make this more flexible is detailed in issue #43. I believe we want to introduce the concept of a `Dimension` object, which is the symbolic equivalent to the `Iteration` loop objects I introduce in PR #59. This would allow users to define which dimensions/loop(s) a particular stencil is applied over and thus allow users to construct multiple loop nests in the form you require for Born. And it maybe even lead to further optimisations, where we construct the "optimal" loop structure after analysing the data dependencies between stencils.
* The other planned feature that would be useful for this problem would be Operator merges, where you would do something like:
```
op_u = Operator(stencil_1)
# Add source to op_u
op_U = Operator(stencil_2)
# Add source to op_U
# Add data read to op_U
op_Born = op_u + op_U
op_Born.apply(...)
```
For this we effectively need to defer the code generation and maybe some of the Propagator pre-processing, so that we can combine the stencils and loops nests when doing the merge. We probably also need some more work towards issue #43, since we need to match the outer dimensions/loops when merging operators.

**Comment by mlange05** [comment] 2016-08-04 09:33
3) Ok, so `SourceLike` is still a very much problem-specific class that was used to figure out how to deal with sparse point interpolation. So it is entirely conceivable that some of this stuff is obsolete now, although I can't say much about the details. The plan is to move stuff that is entirely generic for sparse point interpolation to the parent class `PointData` once we have figured out a generic way to deal with this and provide a neat high-level API. I believe the changes in PR #59 get us a good bit closer to this, but I haven't yet promoted them to `PointData` as I was unsure about a few minor details. I think generalising point interpolation to and from grid data should be one of the immediate follow-ups to PR #59.

**Comment by mloubout** [comment] 2016-08-14 11:12
Another detail concerning the second point, is that we may want to improve the ABC (absorbing boundary conditions) in the future. It would lead to separating the stencil, applied in the full space, from the boundary equations, solved only in the boundary layer afterward. So it will also require to apply a second spacial loop a each time step (each time index of the most outer loop) with different limits.

**Comment by mloubout** [comment] 2016-10-23 20:21
And final detail. It would be good to think about being able to do symbolic operations on `Iteration` object (such as spacial/time derivative of sources term)

**Comment by FabioLuporini** [comment] 2017-06-13 21:08
Maybe it's time to close this. @mlange05 @navjotk @mloubout

**Comment by FabioLuporini** [comment] 2017-06-16 09:37
up

**Comment by FabioLuporini** [comment] 2017-06-27 13:53
Not an issue anymore, closing.

**Closed by FabioLuporini** 2017-06-27 13:53 UTC
