### ISSUE TITLE
Checkpointing drastic slow down due to profiling processing

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#582] opened 2018-05-17 23:16 UTC
Checkpointing became a lot slower. 

Devito 3.2.0:

```
devito @ mathias-2 [mathiaslouboutin]: time python3 examples/checkpointing/checkpointing_example.py 
 range = 462 reps= 5
 prediction of needed forward steps:     1155 => 
 slowdown factor: 3.8889


 advances:  1155
 takeshots:   126
 commands:  1016

real	0m9.972s
user	0m9.290s
sys	0m1.550s
```

The as of today, devito master:

```
devito @ mathias-2 [mathiaslouboutin]: time python3 examples/checkpointing/checkpointing_example.py 
 range = 462 reps= 5
 prediction of needed forward steps:     1155 => 
 slowdown factor: 3.8889


 advances:  1155
 takeshots:   126
 commands:  1016

real	0m40.995s
user	0m38.888s
sys	0m1.896s
```

The mere entirety of the extra 30 seconds is spent in:

```
        # Output summary of performance achieved
        return self._profile_output(args)
```

That is called thousands of times with checkpointing. From my understanding and tests, the calls to `subs` in `summary (@tjb900 ) is taking most of the processing time.

**Comment by FabioLuporini** [comment] 2018-05-18 06:30
@ggorman we need a performance regression test suite

**Comment by mloubout** [comment] 2018-05-18 16:02
As discussed with @FabioLuporini this is not a checkpointing issue but a profiling issue that eats a lot of time with repeated calls to `op.apply`. Needs a No-PROFILING option or something

**Comment by FabioLuporini** [comment] 2018-05-21 13:09
@tjb900 this is apparently due to sympy ``subs`` 😮

**Comment by FabioLuporini** [comment] 2018-05-21 13:10
perhaps we should report the issue to the SymPy folks, as subs shouldn't really take this long for trivial expressions like ours

**Comment by tjb900** [comment] 2018-05-21 13:13
I actually started to look at this, but didn't get as far as a fix.  I think we can do better.

The issue is not the complexity of the expressions, it's that subs(dict) is the same as:

```
for k, v in dict.items():
   expr = expr.subs(k, v)
```

I started to think we could make an "arguments substitutor" which dealt more efficiently with simple expressions, perhaps by starting with `expr.free_symbols` rather than feeding in the full args dict.

**Comment by tjb900** [comment] 2018-05-21 13:15
Doing it that way might be a way to get around my ugly name hack, too.

**Comment by mloubout** [comment] 2018-06-20 13:30
Currently "fixed" with in a not very pretty way for checkpointing, still need `subs` fix.

**Comment by FabioLuporini** [comment] 2018-11-07 13:03
@mloubout @tjb900 @rhodrin I suspect we can close this, as now this sort of expensive profiling is off by default ?

**Comment by rhodrin** [comment] 2018-11-07 13:10
Looking at @mloubout original post regarding the calls to `subs` I think so yes. 
But what changes originally resulted in this issue? That the profiler was added, so some additional profiling that was added?

**Comment by FabioLuporini** [comment] 2018-11-16 08:37
> That the profiler was added, or some additional profiling that was added?

it was just adding '.subs' many PRs ago

closing

**Closed by FabioLuporini** 2018-11-16 08:37 UTC
Labels: backlog, bug
