### ISSUE TITLE
generated functions used by kernel missing some parameters

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#537] opened 2018-04-11 05:59 UTC
```
from devito import (Grid, Operator, TimeFunction, configuration, Eq,
                    ConditionalDimension)

configuration["openmp"] = True
#configuration["compiler"] = "intel"

grid = Grid(shape=(20, 20, 20))
x, y, z = grid.dimensions
time = grid.time_dim
t = grid.stepping_dim
tsave = ConditionalDimension(name='tsave', parent=time, factor=2)

u = TimeFunction(name='u', grid=grid, save=None, time_order=2)
usave = TimeFunction(name='usave', grid=grid, time_dim=tsave,
                     time_order=0, space_order=0)

steps = []

# save of snapshot
steps.append(Eq(usave, u))

# standard laplace-like thing
steps.append(Eq(u.indexed[t+1, x, y, z], u.indexed[t, x, y, z]
                - u.indexed[t-1, x, y, z]
                + u.indexed[t, x-1, y, z] + u.indexed[t, x+1, y, z]
                + u.indexed[t, x, y-1, z] + u.indexed[t, x, y+1, z]
                + u.indexed[t, x, y, z+1] + u.indexed[t, x, y, z+1]))

op = Operator(steps)
op.apply(time=1)
```

Result:

```
99313b14d885f7a9de4d2c44a6c7262c7f5b7231.c(40): error: identifier "time" is undefined
          usave[time / 2][x][y][z] = u[t0][x + 1][y + 1][z + 1];
```

i.e. `time` dimension does not get passed to function

**Comment by tjb900** [comment] 2018-04-11 06:31
Not sure if you want this as a separate issue, but the same .c file has another issue further down which I suspect we will hit once the issue in the title is fixed.  If you comment out the "standard laplace like thing" part above, you instead get this error.

```
2348b8b34565b0ffcf7ddcd114747fbe172de165.c(25): error: parallel loop increment operator must be one of ++, --, +=, or -=
      for (int time = time_m, tsave0 = (time)%(1), t0 = (time)%(1); time <= time_M; time += 1, tsave0 = (time)%(1), t0 = (time)%(1))
```

**Comment by FabioLuporini** [comment] 2018-04-11 06:41
alright, thanks.

An orthogonal note: you don't need ``.indexed`` anymore, I believe. For example, writing ``u[t+1, x, y, z]`` instead of ``u.indexed[t+1, x, y, z]`` should just work. Let me know if it doesn't!

**Comment by FabioLuporini** [comment] 2018-04-11 07:24
@tjb900 can you also get me some asserts for the expected numerical values?

**Comment by tjb900** [comment] 2018-04-11 07:32
It's not complete yet, but this should be right I think:

```
u.data[:] = 0.0
u.data[0, 10, 10, 10] = 1.0

op.apply(time_m=0, time_M=0)

assert np.sum(u.data[0, :, :, :]) == 1.0
assert np.sum(u.data[1, :, :, :]) == 7.0
assert np.all(usave.data[0, :, :, :] == u.data[0, :, :, :])
```

**Comment by tjb900** [comment] 2018-04-11 07:35
Ah, crap.  There's also a typo further up that will make that fail.

Change it to (using the updated syntax):

```
steps.append(Eq(u[t+1, x, y, z], u[t, x, y, z]
                - u[t-1, x, y, z]
                + u[t, x-1, y, z] + u[t, x+1, y, z]
                + u[t, x, y-1, z] + u[t, x, y+1, z]
                + u[t, x, y, z-1] + u[t, x, y, z+1]))
```

**Comment by FabioLuporini** [comment] 2018-04-11 08:41
> Not sure if you want this as a separate issue, but the same .c file has another issue further down which I suspect we will hit once the issue in the title is fixed. If you comment out the "standard laplace like thing" part above, you instead get this error.

I'm ignoring this in #538 because it's a different issue -- and btw, it's actually a duplicate of #320

**Closed** 2018-04-11 15:40 UTC
