### ISSUE TITLE
OPS backend breaking during create_ops_arg 

### ISSUE THREAD

**Issue by maelso** [opesci/devito#908] opened 2019-08-08 20:25 UTC
**Traceback** (most recent call last):
  File "./examples/test/forward.py", line 80, in <module>
    subs=model.spacing_map, name='Forward')
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/backends.py", line 73, in __call__
    return t(*args, **kwargs)
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/operator.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/operator.py", line 185, in __init__
    iet = self._specialize_iet(iet, **kwargs)
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/operator.py", line 69, in _specialize_iet
    trees, n, name_to_ops_dat, ops_block, dims[0]
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/transformer.py", line 61, in opsit
    name_to_ops_dat, par_to_ops_stencil, dims
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/transformer.py", line 231, in create_ops_par_loop
    *[create_ops_arg(p, name_to_ops_dat, par_to_ops_stencil) for p in parameters]
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/transformer.py", line 231, in <listcomp>
    *[create_ops_arg(p, name_to_ops_dat, par_to_ops_stencil) for p in parameters]
  File "/media/cdd4a77d-df70-4379-b548-d27951f6e9c6/Documentos/devito/devito/ops/transformer.py", line 248, in **create_ops_arg
    name_to_ops_dat[p.name]**,
**KeyError: 'utime'**

### **Test file:** 
https://github.com/maelso/devito/blob/local_tests/examples/test/forward.py

**Comment by vincepandolfo** [comment] 2019-08-09 14:28
As said on slack, I believe this is caused by having `save` enabled in your example, which is not currently supported by the OPS backend

**Comment by maelso** [comment] 2019-08-09 17:56
I understood.
It's an open issue because the backend breaks.

**Comment by vincepandolfo** [comment] 2019-08-09 18:10
Yup was writing so that it doesn't get lost 👌

**Comment by maelso** [comment] 2019-08-09 18:31
Nice. :)

**Comment by FabioLuporini** [comment] 2019-10-29 07:29
closing, as the OPS backend is still in its infancy and it's not worth filing these as "issues"

**Closed by FabioLuporini** 2019-10-29 07:29 UTC
