### ISSUE TITLE
Centralised Configuration (Was Configuration File)

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#26] opened 2016-06-07 16:51 UTC
Over time, devito is using quite a few environment variables (4, if I am not mistaken). Since devito is being made as a library, it doesn't make sense to accept command line flags since the actual executable will not always be in our control (since the "end-user" of devito would be writing the executables). The remaining options to take in configuration parameters (like the choice of compiler, compiler flags, whether to enable debug/profiling mode or not) are Environment variables and a configuration file. Environment variables can become difficult to track when the number increases (and at 4, it is already complex). They also make debugging issues harder - setting up the project on a fresh machine will also be much quicker with a default configuration file. 

Maybe we should move to reading these parameters from a config file?

**Comment by navjotk** [comment] 2016-06-09 18:27
4adbae7f68680c84519a9b85c23761159b6ad459 offers an implementation of this. Requesting review and comments.

**Comment by navjotk** [comment] 2016-07-11 18:12
I will make here a list of parameters that I see in the code that could potentially come from a config file:
- Compiler
- Flags
- OpenMP on/off [Can potentially be the BACKEND var]
- Profiling on/off
- Cache blocking on/off
- Block size
- Auto tuning on/off
- Path to isat installation
- Path prefix for generated isat files
- Dependent or Independent search for autotuning
- Auto tune search range
- Path prefix for memmap files
- Dtype (32 bit/64 bit) [Debatable]
- Enable MIC mode or not [Can potentially be the BACKEND var]
- The path for JIT files (in case the user does not want them to go to temp)

**Comment by navjotk** [comment] 2016-10-18 14:50
This is now needed even for first touch to work.

**Comment by mlange05** [comment] 2016-10-18 15:16
OK, to clarify, the need for _a priori_ knowledge arises from the use of a first touch loop being added to memory allocation (see PR #135), which requires us to emulate the same looping pattern if we are using explicit loop blocking.

As a starting point for this I would propose that the internal engine expects some type of `parameters` dictionary, which holds defaults and can in addition be populated via either well-documented environment variables or a fixed config file. We should also be very explicit about which features/flags we need to expose through this mechanism and why, in order to avoid the previous situation where an unnecessarily large number of flags was required to even get baseline performance.

**Comment by navjotk** [comment] 2016-10-18 16:49
These are the required parameters as I see it:
- The `compiler` object
- The `cache_blocking` flag
- Block sizes

**Comment by mlange05** [comment] 2016-10-19 04:54
Hmmm, but how does AT work then - assuming that will be the preferred MO of most users, rather than explicit `cache_blocking`? Do we enable AT via config and then let it write block sizes into the global parameters dictionary?

**Comment by ggorman** [comment] 2016-10-19 20:21
I am assuming that the right behaviour here is for cache_blocking to be picked up if defined, otherwise use AT. We need to be designing primarily for the user (the person who clocks up the most CPU hours)...not the developer/power user. If this is running in a production setting then AT only has to be done once (arguable as part of a deployment/install phase) in the lifetime of the code-machine pair.

**Comment by mlange05** [comment] 2016-10-19 20:40
It's not a question of user vs. developer focus. The problem is that the information that AT creates, the "perfect block size", is required to perform the first touch loop straight after allocating the grid data. This effectively creates the need for a dictionary holding "global information" and a chicken-and-egg situation, because we need to run the first touch loop with the "perfect" block size before we even know about the `Operator` that we need to run AT.

**Comment by navjotk** [comment] 2016-10-20 16:35
A potential solution is to defer initialisation as much as we can, i.e. the initialisation loop is called by the `Propagator` once it has all the information, but just before the actual operator execution.
I had planned this in the first version of `DenseData`. At the time I was thinking that if the OS doesn't actually allocate memory until I actually try to store something in the location, our code shouldn't be bypassing that behaviour by early-allocating memory forcefully. It seems to me that the same behaviour might help with this, except for the autotuning case where the same array would be accessed with different block sizes. I have no solution for that. I don't even think it would be possible without allocating a new block of memory every time - something that would be considered a hack to work around a limitation in our code.

**Comment by navjotk** [comment] 2017-05-18 15:54
Is everyone happy to close this?

**Comment by mlange05** [comment] 2017-05-18 16:10
Do we maybe want to keep this open until we have moved all current parameterisable settings to use this (compiler, DSE, DLE, etc.)? In that case we might also want to have a basic env-var and config-file reader, no?

**Comment by FabioLuporini** [comment] 2017-05-18 22:30
We can close this as there's also #246

**Comment by mlange05** [comment] 2017-05-19 04:19
Ok, I thought supporting config-file + env-vars was kind of the point here, but if people are happy that #246 is enough, I'm happy to close this.

**Comment by navjotk** [comment] 2017-05-19 10:52
My intention was to have a common location for configuration parameters, wherever they might come from. So my original purpose in opening this issue has been fulfilled. 

Having said that, I am happy to keep this open to represent config-file + env-vars now.

**Comment by FabioLuporini** [comment] 2017-05-25 15:05
There is now a fully working centralized configuration mechanism, although reading from file is not supported yet.

**Comment by mlange05** [comment] 2017-06-06 08:51
Ok, following the last changes, the defaulting and env readers look good for this, and the handling of global state via callbacks seems nice too. Are we still interested in pursuing the config file reader, and if so should this be done in a separate issue? I'd be happy to close this otherwise. Thoughts? @navjotk @ggorman

**Comment by navjotk** [comment] 2017-06-06 10:37
I think reading from a file is a nice feature to have. Also, we aren't too far away from having it. Can we please keep this issue open a little while longer until one of us can get to implementing this?

**Comment by mlange05** [comment] 2017-06-06 10:42
Ok cool.

**Comment by navjotk** [comment] 2018-03-19 16:54
Closing if no one objects.

**Comment by FabioLuporini** [comment] 2018-03-20 07:31
OK, closing this

**Closed by FabioLuporini** 2018-03-20 07:31 UTC
