### ISSUE TITLE
dependent writes to single variable collapsed to final one rather than sequentialised

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#506] opened 2018-03-02 05:24 UTC
Came across this while working on a source injection example:

```
from devito import Grid, Function, Operator, Inc
import numpy as np

grid = Grid(shape=(10,10))
u = Function(name='u', grid=grid, space_order=0)

op = Operator([Inc(u,u+1.0), Inc(u,u+2.0)])
u.data[:] = 0.0
op.apply()

# Array actually contains all 2s
assert np.all(u.data[:] == 3)
```

I don't have a use case for this - all the real injection examples work.  However the above result seems to indicate something dangerous is happening.  This is especially true considering how similar the above example is to the idiom we typically use to perform injection in the wave equation case:

[Eq(u.forward, blah blah), Inc(u.forward, u.forward+source terms)]

In all the cases so far we might just be getting saved by the fact that we generate a separate loop structure for the source injection?

Is this an ambiguity in the DSL?  I had assumed that the sequence of expressions passed to an operator is considered to be ordered, but perhaps this is a misunderstanding on my part?

**Comment by FabioLuporini** [comment] 2018-03-02 08:56
The generated code looks buggy, as it's missing an equation

> Is this an ambiguity in the DSL? I had assumed that the sequence of expressions passed to an operator is considered to be ordered, but perhaps this is a misunderstanding on my part?

No, the compiler tries to be smarter than that. Through data dependence analysis, it can also fuse later equations with earlier ones, even though there are some equations in the middle between them -- as long as those equations do not induce data dependences.

**Comment by FabioLuporini** [comment] 2018-03-02 09:06
> In all the cases so far we might just be getting saved by the fact that we generate a separate loop structure for the source injection?

I checked, and no the issue is that the compiler is getting confused by two consecutive identical LHSs
I'll have to come up with a proper fix for this

**Closed** 2018-03-16 19:43 UTC
